title: Inspires Canada
description: More than just robots!
description_fr: Plus que des robots!
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
url: https://acharraggi.github.io/firstinspires.ca
