title: FIRST Inspires Canada
description: FIRST is a not-for-profit organization devoted to helping young people discover and develop a passion for science, technology, engineering, and math (STEM) through hands-on robotics challenges.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
